/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chan_mulan_Mulan */

#ifndef _Included_com_chan_mulan_Mulan
#define _Included_com_chan_mulan_Mulan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chan_mulan_Mulan
 * Method:    render
 * Signature: (Ljava/lang/String;Lcom/chan/mulan/renderer/MarkdownRenderer;)V
 */
JNIEXPORT void JNICALL Java_com_chan_mulan_Mulan_render
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
